sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEGH22JHYSnhXJuJKAuGK34xDttLVYdbSADT3sQjFpHu rpoisel
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5ICtYQXByQSA2QWFr
            R3RJV095MWswM1puNGlRM3BGTU0wL0EyOWdNb2t0MVZqMjBzMEFJCllKWVBpT3Rz
            QTVNWXlFbzVYbEVoWVVUdXJodEdzOXlzdHA0Lzc5aWJBU2sKLS0tIGdxTFRXNVJY
            N3JUeUJ1OW8zenRwKzlYdGdsamtFU0UwalVBNmFCTndjSVkKleEN08fzOn+JBBt1
            wuCoYCJ6DWRl6cNDFEQwmIUwRKaYsOMjHIS317F8uWnq0UvbTpmjROyO4Ib+H+U7
            1oHD0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:06:39Z"
    mac: ENC[AES256_GCM,data:1i9t6ZaCKkW6RmoFeexqFfp7DOeSUryDJvvsdKEzvhBolDXsT7Vr7+HyP2LVl+O5WLQs1WHbFjnDFtyNWg8e8wOX0oy4cw6N5rYv7AteawWjtHm05X+R4t0OhI7Mln4AU7Lm4bZqqQlA20a5hDZStQEJwxPIeKemNPgxgG2SYw0=,iv:qDXEM+1JrQGphJ70amasu+Q7E5o0k8dWkotB2Pr6v2w=,tag:6ImmQsDf09SO+3WFCtf7wg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
