---
x-common-build-args: &common-build-args
  TZ: ${TZ:-Europe/Vienna}
  ZSH_IN_DOCKER_VERSION: 1.2.1

x-common-build: &common-build
  context: .
  dockerfile: Dockerfile
  args:
    <<: *common-build-args

x-common-service: &common-service
  build:
    <<: *common-build
  cap_add:
  - NET_ADMIN
  - NET_RAW
  environment:
    NODE_OPTIONS: --max-old-space-size=4096
    POWERLEVEL9K_DISABLE_GITSTATUS: "true"
  command: tail -f /dev/null
  user: node
  working_dir: /workspace

services:
  claude-code:
    <<: *common-service
    build:
      <<: *common-build
      target: claude-code
      args:
        <<: *common-build-args
        CLAUDE_CODE_VERSION: 2.1.220
        # https://github.com/agentclientprotocol/claude-agent-acp
        CLAUDE_AGENT_ACP_VERSION: 0.64.2
    volumes:
    - ${AGENT_CIRCUS_WORKSPACE:-..}:/workspace:cached
    - ${HOME}/.cache:/home/node/.cache
    environment:
      AGENT_TYPE: claude-code
      NODE_OPTIONS: --max-old-space-size=4096
      CLAUDE_CONFIG_DIR: /home/node/.claude
      POWERLEVEL9K_DISABLE_GITSTATUS: "true"

  codex:
    <<: *common-service
    build:
      <<: *common-build
      target: codex
      args:
        <<: *common-build-args
        # https://github.com/openai/codex
        CODEX_VERSION: 0.146.0
        # https://github.com/agentclientprotocol/codex-acp
        CODEX_ACP_VERSION: 1.1.9
    volumes:
    - ${AGENT_CIRCUS_WORKSPACE:-..}:/workspace:cached
    - ${HOME}/.cache:/home/node/.cache
    environment:
      AGENT_TYPE: codex

  mistral-vibe:
    <<: *common-service
    build:
      <<: *common-build
      target: mistral-vibe
      args:
        <<: *common-build-args
    volumes:
    - ${AGENT_CIRCUS_WORKSPACE:-..}:/workspace:cached
    - ${HOME}/.cache:/home/node/.cache
    environment:
      AGENT_TYPE: mistral-vibe

  opencode:
    <<: *common-service
    build:
      <<: *common-build
      target: opencode
      args:
        <<: *common-build-args
        # https://www.npmjs.com/package/opencode-ai
        OPENCODE_VERSION: 1.18.11
    volumes:
    - ${AGENT_CIRCUS_WORKSPACE:-..}:/workspace:cached
    - ${HOME}/.cache:/home/node/.cache
    environment:
      AGENT_TYPE: opencode
